name: "Build-Release-Todo-App-$(Build.BuildId)"

trigger:
  branches:
    include:
      - main

pool:
  name: "devops-pool-x43ywukzvc6uu"

variables:
  - name: SqlServer
    value: "sql-x43ywukzvc6uu.46cc585a7110.database.windows.net"
  - name: SqlDatabase
    value: "sqldbx43ywukzvc6uu"
  - name: WebApp
    value: "app-x43ywukzvc6uu"
  - name: ResourceGroup
    value: "rg-securitypocs20241101"
  - name: ManagedIdentityObjectId
    value: "15b7a253-657f-4c41-a8f8-fd631fcbf6f8"

steps:
  - checkout: self
    clean: true

  - pwsh: |
      dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)/publish
    displayName: "Run dotnet publish"
    workingDirectory: "src/Joonasw.SeriouslySecuringAzurePaas.TodoApp.Web"

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: "$(Build.ArtifactStagingDirectory)/publish"
      includeRootFolder: false
      archiveType: "zip"
      archiveFile: "$(Build.ArtifactStagingDirectory)/web-$(Build.BuildId).zip"
      replaceExistingArchive: true
    displayName: "Archive files"

  - pwsh: |
      dotnet tool restore
      dotnet ef migrations script -o $(Build.ArtifactStagingDirectory)/migration.sql --idempotent -p Joonasw.SeriouslySecuringAzurePaas.TodoApp.Data -s Joonasw.SeriouslySecuringAzurePaas.TodoApp.Web
    displayName: "Generate EF migration script"
    workingDirectory: "src"

  - pwsh: |
      az login --identity --username $(ManagedIdentityObjectId)
      $accessToken = az account get-access-token --resource https://database.windows.net --query accessToken -o tsv
      Invoke-SqlCmd -ServerInstance "$(SqlServer)" -Database "$(SqlDatabase)" -AccessToken $accessToken -InputFile "$(Build.ArtifactStagingDirectory)/migration.sql"
    displayName: "Deploy EF migration script"

  - task: AzureWebApp@1
    inputs:
      azureSubscription: "seriously-securing-azure-paas"
      appType: "webApp"
      appName: "$(WebApp)"
      package: "$(Build.ArtifactStagingDirectory)/web-$(Build.BuildId).zip"
      deployToSlotOrASE: true
      deploymentMethod: "runFromPackage"
      slotName: "production"
      resourceGroupName: "$(ResourceGroup)"
    displayName: "Deploy to Azure App Service"
