name: "Build-Release-Todo-App-$(Build.BuildId)"

trigger:
  branches:
    include:
      - main

pool:
  name: "devops-pool-757m7v3o4cgdk"

steps:
  - checkout: self
  - pwsh: |
      Write-Host "Hello, World!"
    displayName: "Test"